// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzyVFFnKV7ZYqES32BIOLC3CppOqnQUyk',
    appId: '1:406923001682:web:95ea16438fdda49b70848b',
    messagingSenderId: '406923001682',
    projectId: 'lingoleap-9859b',
    authDomain: 'lingoleap-9859b.firebaseapp.com',
    storageBucket: 'lingoleap-9859b.firebasestorage.app',
    measurementId: 'G-W5QC672HLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFWeE-EEkxJ6vCZYPNoxHxjtZ6hoHcFAI',
    appId: '1:406923001682:android:f3e67955076c133670848b',
    messagingSenderId: '406923001682',
    projectId: 'lingoleap-9859b',
    storageBucket: 'lingoleap-9859b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8TdxSej7mRACvK2JioE68dT2iHvTzu7U',
    appId: '1:406923001682:ios:ab7fdb039e23aeeb70848b',
    messagingSenderId: '406923001682',
    projectId: 'lingoleap-9859b',
    storageBucket: 'lingoleap-9859b.firebasestorage.app',
    iosBundleId: 'com.example.lingoleap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8TdxSej7mRACvK2JioE68dT2iHvTzu7U',
    appId: '1:406923001682:ios:ab7fdb039e23aeeb70848b',
    messagingSenderId: '406923001682',
    projectId: 'lingoleap-9859b',
    storageBucket: 'lingoleap-9859b.firebasestorage.app',
    iosBundleId: 'com.example.lingoleap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzyVFFnKV7ZYqES32BIOLC3CppOqnQUyk',
    appId: '1:406923001682:web:20e1fd3f99b4f11170848b',
    messagingSenderId: '406923001682',
    projectId: 'lingoleap-9859b',
    authDomain: 'lingoleap-9859b.firebaseapp.com',
    storageBucket: 'lingoleap-9859b.firebasestorage.app',
    measurementId: 'G-HL0S6VLWPH',
  );
}
